name: expenses_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: lib/assets/fonts/OpenSans-Bold.ttf
        - asset: lib/assets/fonts/OpenSans-Regular.ttf
          weight: 800
    - family: Quicksand
      fonts:
        - asset: lib/assets/fonts/Quicksand-Light.ttf
        - asset: lib/assets/fonts/Quicksand-Regular.ttf
          weight: 600
